#!/bin/sh

# Author: Remy Themsen
# Created: 31/03/2016
#
# The purpose of this script is to echo out a formatted string using icons from 
# FontAwesome (https://fortawesome.github.io/) it was created for outputting into 
# Conky (https://github.com/brndnmtthws/conky), and more specifically through conky 
# Directly into i3bar (Part of the i3 window manager.
# NOTE: that the script assumes there to be two batteries, this is specifically 
# 			for the Thinkpad >T440 series. 

# Get current maximum charge.
bat_0_max=$(cat /sys/class/power_supply/BAT0/energy_full)
bat_1_max=$(cat /sys/class/power_supply/BAT1/energy_full)

total_max=$(($bat_0_max+$bat_1_max))

# Calculate percentage left as current charge vs. maximum. 
bat0=$(cat /sys/class/power_supply/BAT0/energy_now)
bat1=$(cat /sys/class/power_supply/BAT1/energy_now)
charge=$((($bat0 + $bat1)*100/$total_max))

#Is it charging ?
is_0_charging=$(cat /sys/class/power_supply/BAT0/uevent | grep -oP '_SUPPLY_STATUS=\K\w+')
is_1_charging=$(cat /sys/class/power_supply/BAT1/uevent | grep -oP '_SUPPLY_STATUS=\K\w+')

#Determining which icon to show
if [ "$is_0_charging" == "Charging" ] || [ "$is_1_charging" == "Charging" ]
then
		icon=
elif [ $charge -gt 90 ]
then
		icon=
elif [ $charge -gt 75 ]
then
		icon=
elif [ $charge -gt 40 ]
then
		icon=
elif [ $charge -gt 10 ]
then
		icon=
else #It's Near empty
		icon=
fi

#Formatting and printing result
echo $icon $charge%
